language: go

sudo: false

matrix:
  include:
    - go: "1.8.x"
    - go: "1.9.x"
    - go: "1.10.x"
    - go: "1.11.x"
      env: GO111MODULE=off
    - go: "1.11.x"
      env: GO111MODULE=on
  before_install:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
  script:
    - go test -v -parallel=10 -covermode=count -coverprofile=coverage.out
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci